### ISSUE TITLE
use a custom icon for atoum's test files

### ISSUE THREAD

**Issue by agallou** [agallou/phpstorm-plugin#29]
With this, if will be easier to distinct the file from the tested file.

**Comment by mnapoli** [comment]
:+1:

**Comment by agallou** [comment]
@mnapoli here is what it will look like : 
![capture du 2016-01-25 21 38 18](https://cloud.githubusercontent.com/assets/320372/12564157/1857558c-c3ae-11e5-950a-4fb5e7ea4e51.png)

**Comment by mnapoli** [comment]
looking good!
